# ########################################################################
#
# Documentation Ricgraph - Research in context graph
#
# ########################################################################
#
# MIT License
# Copyright (c) 2025 Rik D.T. Janssen
#
# ########################################################################
#
# This file is the Quarto config file to generate the Ricgraph
# website.
#
# Note that Quarto will be run in directory .../source_docs_website/website
# (the other Quarto build options run in .../source_docs_website).
# This is necessary to have the html files directly after the website link, 
# like in "www.ricgraph.eu/what-is-ricgraph.hmtl" instead of
# "www.ricgraph.eu/website/what-is-ricgraph.hmtl".
#
# Original version Rik D.T. Janssen, February 2025.
#
# ########################################################################

project:
  # See remark above, Quarto is run in dir 'website'.
  output-dir: ../../build_website
  type: website
  render:
    # The first here will be referred to in 'index.html'.
    - what-is-ricgraph.md
    - "*.md"
  
website:
  title: "Website Ricgraph - Research in context graph"
  description: "This is the website for Ricgraph - Research in context graph"
  favicon: images/favicon.ico
  search: true
  back-to-top-navigation: true
  sidebar:
    border: false
    title: "Research in context graph"
    style: docked
    logo: images/ricgraph_logo.png
    logo-alt: "Ricgraph logo"
    search: true
    background: primary
    collapse-level: 1
    pinned: true
    contents:
      - text: "What is Ricgraph?"
        href: what-is-ricgraph.md
      - text: "Learn more"
        href: learn-more-about-ricgraph.md
      - text: "Read more"
        href: read-more-about-ricgraph.md
      - text: "Read documentation"
        href: "https://docs.ricgraph.eu"
      - text: "Get Ricgraph"
        href: get-ricgraph.md
      - text: "Contact"
        href: contact.md
    footer: >
          [![DOI Ricgraph software](https://img.shields.io/badge/DOI%20software-10.5281/zenodo.7524314-blue)](https://doi.org/10.5281/zenodo.7524314)
          [![DOI reference Ricgraph publication](https://img.shields.io/badge/DOI%20publication-10.1016%2Fj.softx.2024.101736-blue)](https://doi.org/10.1016/j.softx.2024.101736)
          <a href="https://www.ricgraph.eu"><img alt="Ricgraph website" src="https://img.shields.io/badge/website-www.ricgraph.eu-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAatAAAGrQEzE5+4AAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAABN0RVh0VGl0bGUAUmljZ3JhcGggaWNvbtfYluIAAAAXdEVYdEF1dGhvcgBSaWsgRC5ULiBKYW5zc2VuFiXm4QAAABl0RVh0RGVzY3JpcHRpb24AUmljZ3JhcGggaWNvblxqBnoAAABEdEVYdENvcHlyaWdodABDQyBBdHRyaWJ1dGlvbiBodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9ieS80LjAvaRDXXQAAA5FJREFUWIW1l1uIVlUUx3/ON2aTiBlWpKh0eQmpIB9CSaqBniwQyqKLYQQlwZTRQ1OUNkTMQOWUBIbWdIdkKCqE6KaRgVRWPlQWPVhRQdroxMzgXHJ+Pew1zMdpf5eZ+dqwOeesy97/tdf6770PKhV6q/qJ2q8eUrvUlir20+pN5NstwEdAC9AN7AM2AXuB5go+02sZVHPVY2qv2lQmX63+o7Y1cgVywtWmtiKj26O+U8fAzWq7+q06pH6h3lxvCk6N53BGN1ymr9Z2AY8DB+P5F/A6sLmeFJyhjqhbC/ILIpotNaK/NlawGHGXOqaeXysFqA/FIK+o16v3qX+qP6vzagDYGnZF+enquLqhXF6pojuBfmALsB4YA2YBHcBAjeWfA4xk5GPAOMUU1lFQi9Q56i71qDq/hv2tEemVBXlbyC+uJwW5fq46rHbWsLtTHY166VDXqc+aKLyjaD9V3narJ9SlFfQPRO28ob6gDsb3qPq8OnumABaofer76iMmRrSqJXV7TPaMkxtYKcAeU5/MjTlVAM3qlzFRv3o83n9RT6r3VvB7TT3cCAAPm3K5QZ0VfX3Ieqv4rQugF80UwGF1Z0a+Xf2tit9i0yb0o/quusmoh/KtuAQsB1YAp1Tg9zLg64zuK2AxsBZYUNAtAfYDo8BPwGnAE8BnQMsEwjXqH062AXVjWQRLTZQaUnsyEe4wUVQT139QX1bvVj9Vf1fPK7O/POw7US+LHH6gXh3Knhhsm/qeqcBOqN/E+12mCi+pd4T/ZnW5epuJCQfCdly9JwN6p/o9MfFB/8vRXhN/D5n4vTAmfDHADcZKqb5qYkhxkgtDf11G96h6HBNHOzIGN4Tzooxupem8f1BdldGX96PqSwVZyUTnPc1AH7AwU1hnAieBvzO6/dHraR3Atpinh3TNawcuBVqJfA2ql5QhPMd0pH5YI7p6enus5IiTrU+9ydgH5qnfmaryTdOu1acesXB5mEa/wsT/baZtfKLI507YTBi2RFHsi9w8rZ41jQlL6pJ4nm2i3+em4zzrM9PlLQ+g20lWDKm/xkouq+bbKABvRwq71LXqY/F9wHRe/K8AroqobyzIrwn5mmr+lf6MptJWku6JvQX5buAIsKqacyMADJMOr+IFt4l0gOX+LxoKYC8wG7i/IG8D5gMfV/VuUBE+FfnebTqU3orv52r5NgoA6u2mf8AB016ysRYDVP4FRtPJ+PNff84AAAAASUVORK5CYII="></a>
          <a href="https://docs.ricgraph.eu"><img alt="Ricgraph documentation website" src="https://img.shields.io/badge/doc%20website-docs.ricgraph.eu-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAatAAAGrQEzE5+4AAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAABN0RVh0VGl0bGUAUmljZ3JhcGggaWNvbtfYluIAAAAXdEVYdEF1dGhvcgBSaWsgRC5ULiBKYW5zc2VuFiXm4QAAABl0RVh0RGVzY3JpcHRpb24AUmljZ3JhcGggaWNvblxqBnoAAABEdEVYdENvcHlyaWdodABDQyBBdHRyaWJ1dGlvbiBodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9ieS80LjAvaRDXXQAAA5FJREFUWIW1l1uIVlUUx3/ON2aTiBlWpKh0eQmpIB9CSaqBniwQyqKLYQQlwZTRQ1OUNkTMQOWUBIbWdIdkKCqE6KaRgVRWPlQWPVhRQdroxMzgXHJ+Pew1zMdpf5eZ+dqwOeesy97/tdf6770PKhV6q/qJ2q8eUrvUlir20+pN5NstwEdAC9AN7AM2AXuB5go+02sZVHPVY2qv2lQmX63+o7Y1cgVywtWmtiKj26O+U8fAzWq7+q06pH6h3lxvCk6N53BGN1ymr9Z2AY8DB+P5F/A6sLmeFJyhjqhbC/ILIpotNaK/NlawGHGXOqaeXysFqA/FIK+o16v3qX+qP6vzagDYGnZF+enquLqhXF6pojuBfmALsB4YA2YBHcBAjeWfA4xk5GPAOMUU1lFQi9Q56i71qDq/hv2tEemVBXlbyC+uJwW5fq46rHbWsLtTHY166VDXqc+aKLyjaD9V3narJ9SlFfQPRO28ob6gDsb3qPq8OnumABaofer76iMmRrSqJXV7TPaMkxtYKcAeU5/MjTlVAM3qlzFRv3o83n9RT6r3VvB7TT3cCAAPm3K5QZ0VfX3Ieqv4rQugF80UwGF1Z0a+Xf2tit9i0yb0o/quusmoh/KtuAQsB1YAp1Tg9zLg64zuK2AxsBZYUNAtAfYDo8BPwGnAE8BnQMsEwjXqH062AXVjWQRLTZQaUnsyEe4wUVQT139QX1bvVj9Vf1fPK7O/POw7US+LHH6gXh3Knhhsm/qeqcBOqN/E+12mCi+pd4T/ZnW5epuJCQfCdly9JwN6p/o9MfFB/8vRXhN/D5n4vTAmfDHADcZKqb5qYkhxkgtDf11G96h6HBNHOzIGN4Tzooxupem8f1BdldGX96PqSwVZyUTnPc1AH7AwU1hnAieBvzO6/dHraR3Atpinh3TNawcuBVqJfA2ql5QhPMd0pH5YI7p6enus5IiTrU+9ydgH5qnfmaryTdOu1acesXB5mEa/wsT/baZtfKLI507YTBi2RFHsi9w8rZ41jQlL6pJ4nm2i3+em4zzrM9PlLQ+g20lWDKm/xkouq+bbKABvRwq71LXqY/F9wHRe/K8AroqobyzIrwn5mmr+lf6MptJWku6JvQX5buAIsKqacyMADJMOr+IFt4l0gOX+LxoKYC8wG7i/IG8D5gMfV/VuUBE+FfnebTqU3orv52r5NgoA6u2mf8AB016ysRYDVP4FRtPJ+PNff84AAAAASUVORK5CYII="></a> 
          <a href="https://github.com/UtrechtUniversity/ricgraph"><img alt="GitHub Ricgraph" src="https://img.shields.io/badge/GitHub-UtrechtUniversity/ricgraph-blue?logo=github"></a>
          <img alt="GitHub release date" src="https://img.shields.io/github/release-date/UtrechtUniversity/ricgraph?color=%234c1&logo=github">
          <a href="https://github.com/UtrechtUniversity/ricgraph/releases"><img alt="GitHub latest release" src="https://img.shields.io/github/release/UtrechtUniversity/ricgraph?color=%234c1&logo=github"></a>
          <img alt="GitHub commits since latest release" src="https://img.shields.io/github/commits-since/UtrechtUniversity/ricgraph/latest?color=%234c1&logo=github">
          <img alt="GitHub last commit" src="https://img.shields.io/github/last-commit/UtrechtUniversity/ricgraph?color=%234c1&logo=github">
          <a href="https://pypi.org/project/ricgraph"><img alt="PyPI version" src="https://img.shields.io/pypi/v/ricgraph?label=PyPI%20version&color=%234c1&logo=pypi&logoColor=ffffff"></a>
          <a href="https://pypistats.org/packages/ricgraph"><img alt="PyPI downloads" src="https://img.shields.io/pypi/dm/ricgraph?label=PyPI%20downloads&color=%234c1&logo=pypi&logoColor=ffffff"></a>
  page-footer: 
    background: primary
    left:
      # Do not change '#XX.YY#' below, it will be modified by the Makefile.
      - text: >
          You are visiting one of the Ricgraph websites 
          <a href="https://www.ricgraph.eu">
          www.ricgraph.eu</a>,
          <a href="https://www.ricgraph.nl">
          www.ricgraph.nl</a>, or
          <a href="https://www.ricgraph.com">
          www.ricgraph.com</a>.

format:
  html:
    grid:
      # If you change this, also change "body.docked .sidebar-navigation"
      # key 'width' in ricgraph.scss.
      sidebar-width: 400px
    theme: 
      - cosmo
      - ../ricgraph.scss
    toc: true
    lightbox: true
    filters:
      - ../convert_scripts/fix_mdtohtml_links.lua
    # The font used on the webpages is determined by the 'fonts.' below and 
    # a setting in ricgraph.scss.
    include-in-header:
      - text: |
          <link href='https://fonts.googleapis.com/css?family=Open+Sans' 
          rel='stylesheet' type='text/css'>

keywords:
  - "Research in context graph"
  - "Ricgraph"
  - "Ricgraph Explorer"
  - "Ricgraph REST API"
  - "Data enrichment"
  - "Data harvesting"
  - "Data linking"
  - "Enrichment"
  - "Graph"
  - "Graph database"
  - "Harvest"
  - "Harvest data"
  - "Harvester"
  - "Knowledge graph"
  - "Linked data"
  - "Metadata"
  - "Utrecht University"
  - "Visualization"

