# ########################################################################
#
# Documentation Ricgraph - Research in context graph
#
# ########################################################################
#
# MIT License
# Copyright (c) 2025 Rik D.T. Janssen
#
# ########################################################################
#
# This file is the Quarto config file to generate the full Ricgraph
# documentation.
#
# Original version Rik D.T. Janssen, February 2025.
#
# ########################################################################

project:
  output-dir: ../build_documentation
  type: book

lang: en

book:
  title: "Documentation Ricgraph - Research in context graph"
  author: "Rik D.T. Janssen, Utrecht University, ORCID 0000-0001-9510-0802"
  chapters:
    - index.md
    # The Makefile will add a part for the full documentation.
    - docs/ricgraph_documentation_intro.md
    - README.md
    - docs/ricgraph_install_configure.md
    - docs/ricgraph_harvest_scripts.md
    - docs/ricgraph_explorer.md
    - docs/ricgraph_pubs_pres_news_use_ment.md
    - docs/ricgraph_example_use_videos.md
    - docs/ricgraph_as_server.md
    - docs/ricgraph_containerized.md
    - docs/ricgraph_backend_neo4j.md
    - docs/ricgraph_backend_memgraph.md
    - docs/ricgraph_restapi.md
    - docs/ricgraph_restapi_gendoc.md
    - docs/ricgraph_details.md
    - docs/ricgraph_misc_scripts.md
    - docs/ricgraph_script_writing.md
    - docs/ricgraph_comparison.md
    - docs/ricgraph_known_bugs.md
    - docs/ricgraph_toc_documentation.md
    - docs/ricgraph_index_documentation.md

format:
  pdf:
    documentclass: scrreprt
    papersize: a4
    # The following does not work unfortunately since 'longtable' 
    # (quarto's LaTeX table environment) does not work in 2-column mode.
    # classoption: 
    #   - landscape
    #   - twocolumn
    fig-format: png
    fig-pos: "H"
    # The table of contents is generated in file index.md.
    # We use the \tableofcontents LaTeX command in that file.
    raw_tex: true
    toc: false
    # toc-depth: 2
    geometry:
      - footskip=1cm
      - left=3cm
      - right=2cm
      - top=2.5cm
      - bottom=2.5cm
      - columnsep=1cm
      - heightrounded
    # To use font Merriweather & Open Sans, they should be installed on 
    # your computer, as a system font (not as a LaTeX font).
    mainfont: "Merriweather"
    sansfont: "Open Sans"
    fontsize: 9pt
    linestretch: 1.15
    breaklines: true
    filters:
      - convert_scripts/fix_path_to_externalfiles.lua
    # Do not change '#XX.YY#' below, it will be modified by the Makefile.
    include-in-header:
      text: |
        \usepackage{scrlayer-scrpage}
        \pagestyle{scrheadings}
        \cfoot{}
        \ifoot{\parbox[t]{\dimexpr\textwidth-1cm\relax}{
          \setstretch{0.6}
          \textrm{\footnotesize
          This is documentation for version #XX.YY# of Ricgraph - Research 
          in context graph.
          For more information about Ricgraph, Ricgraph Explorer, and the
          Ricgraph REST API, please read the reference publication 
          \href{https://doi.org/10.1016/j.softx.2024.101736}
          {https://doi.org/10.1016/j.softx.2024.101736}, visit the website 
          \href{https://www.ricgraph.eu}{www.ricgraph.eu}, 
          or go to the GitHub
          repository \href{https://github.com/UtrechtUniversity/ricgraph}
          {https://github.com/UtrechtUniversity/ricgraph.}}}}
        \ofoot{\pagemark} 
        % For UU yellow bar at the left and the logo.
        \usepackage[cmyk]{xcolor}
        \definecolor{uuyellow}{cmyk}{0, 0.15, 1, 0}
        \usepackage{background}
        \backgroundsetup{
          scale=1, color=uuyellow, opacity=1, angle=0,
          position=current page.west, vshift=-0.5\paperheight,
          contents={\begin{tikzpicture}[remember picture,overlay]
                    \fill[uuyellow] (0,0) rectangle (2cm,\paperheight);
                    \node[anchor=south west, inner sep=0pt] at (0.5cm,2.5cm) {
                       \includegraphics[height=1.0cm, angle=90]{docs/images/ricgraph_logo_1000.png}};\end{tikzpicture}}
        }

keywords:
  - "Research in context graph"
  - "Ricgraph"
  - "Ricgraph Explorer"
  - "Ricgraph REST API"
  - "Data enrichment"
  - "Data harvesting"
  - "Data linking"
  - "Enrichment"
  - "Graph"
  - "Graph database"
  - "Harvest"
  - "Harvest data"
  - "Harvester"
  - "Knowledge graph"
  - "Linked data"
  - "Metadata"
  - "Utrecht University"
  - "Visualization"

