# ########################################################################
#
# Documentation Ricgraph - Research in context graph
#
# ########################################################################
#
# MIT License
# Copyright (c) 2025 Rik D.T. Janssen
#
# ########################################################################
#
# This file is the Quarto config file to generate the Ricgraph
# documentation website.
#
# Original version Rik D.T. Janssen, February 2025.
#
# ########################################################################

project:
  output-dir: ../build_documentation
  type: website
  render:
    # The first here will be referred to in 'index.html'.
    - docs/ricgraph_documentation_intro.md
    - "README.md"
    - "docs/*.md"
    - "docs/newsletters/*.md"
  resources:
    - "docs/images/icons/android/*"
    - "docs/images/ricgraph-docs-screenshot-*"
  
lang: en
description-meta: "Ricgraph (Research in context graph) enables the exploration of researchers, teams, their results, collaborations, skills, projects, and the relations between these items."
author-meta: "Rik D.T. Janssen"
# Meta 'keywords' is at the end of this file.

website:
  title: "Documentation Ricgraph - Research in context graph"
  favicon: favicon.ico
  search: true
  back-to-top-navigation: true
  sidebar:
    border: false
    title: "Documentation Research in context graph"
    style: docked
    logo: docs/images/ricgraph_logo.png
    logo-alt: "Ricgraph logo"
    search: true
    background: primary
    collapse-level: 1
    pinned: true
    contents:
      - text: "Ricgraph docs intro"
        href: docs/ricgraph_documentation_intro.md
      - text: "Tutorial Ricgraph"
        href: docs/ricgraph_tutorial.md
      - text: "Contact"
        href: README.md#contact
      - text: "Pilot Open Ricgraph demo server"
        href: "https://www.ricgraph.eu/pilot-project-open-ricgraph-demo-server.html"
      - section: "Full documentation"
        contents:
          - text: "Readme Ricgraph"
            href: README.md
          - text: "Install"
            href: docs/ricgraph_install_configure.md
          - text: "Harvest sources"
            href: docs/ricgraph_harvest_scripts.md
          - text: "Explore"
            href: docs/ricgraph_explorer.md
          - text: "Read publications, presentations, and more"
            href: docs/ricgraph_outreach.md
          - section: "More options"
            contents:
              - section: "Installation options"
                contents:
                  - href: docs/ricgraph_as_server.md
                  - href: docs/ricgraph_containerized.md
              - section: "Graph database backends"
                contents:
                  - text: "Ricgraph with Neo4j"
                    href: docs/ricgraph_backend_neo4j.md
                  - text: "Ricgraph with Memgraph"
                    href: docs/ricgraph_backend_memgraph.md
              - text: "Use the Ricgraph REST API"
                href: docs/ricgraph_restapi.md
              - text: "Read about details"
                href: docs/ricgraph_details.md
              - text: "Run miscellaneous scripts"
                href: docs/ricgraph_misc_scripts.md
              - text: "Write Ricgraph scripts"
                href: docs/ricgraph_script_writing.md
              - text: "Compare Ricgraph to others"
                href: docs/ricgraph_comparison.md
              - text: "Read about known bugs"
                href: docs/ricgraph_known_bugs.md
              # The following section is necessary, because it ensures
              # that the left menubar is present when you click on one
              # of these items. Otherwise, without this, there is no way
              # to get the left sidebar, which gives a weird user
              # experience.
              - section: "Don't look here &#9786;"
                contents:
                  - text: "Table of contents"
                    href: docs/ricgraph_toc_documentation.md
                  - text: "Index"
                    href: docs/ricgraph_index_documentation.md
                  - text: "REST API generated doc"
                    href: docs/ricgraph_restapi_gendoc.md
                  - text: "Newsletter April 2024"
                    href: docs/newsletters/240400-Ricgraph_newsletter_April_2024.md
                  - text: "Newsletter July 2024"
                    href: docs/newsletters/240700-Ricgraph_newsletter_July_2024.md
      - text: "Tutorial pdf"
        href: ricgraph_tutorial.pdf
      - text: "Full documentation pdf"
        href: ricgraph_fulldocumentation.pdf
    footer: >
          [![DOI Ricgraph software](https://img.shields.io/badge/software-10.5281/zenodo.7524314-blue?logo=doi&logoColor=fff)](https://doi.org/10.5281/zenodo.7524314)
          [![DOI reference Ricgraph publication](https://img.shields.io/badge/publication-10.1016%2Fj.softx.2024.101736-blue?logo=doi&logoColor=fff)](https://doi.org/10.1016/j.softx.2024.101736)
          [![DOI Ricgraph collaborations preprint](https://img.shields.io/badge/preprint-10.2139%2Fssrn.5524439-blue?logo=doi&logoColor=fff)](https://doi.org/10.2139/ssrn.5524439)
          <a href="https://www.ricgraph.eu"><img alt="Ricgraph website" src="https://img.shields.io/badge/website-www.ricgraph.eu-blue?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI3MC43NTIiIGhlaWdodD0iNzAuNzYxIiB2aWV3Qm94PSIwIDAgMTguNzIgMTguNzIyIj48ZyBzdHlsZT0ic3Ryb2tlOiNmZmY7c3Ryb2tlLW9wYWNpdHk6MSIgdHJhbnNmb3JtPSJtYXRyaXgoMS4wNTIwNCAwIDAgMS4wNTIwNCAtNjguMzM1IC0xMy4wODMpIj48Y2lyY2xlIGN4PSI2OS44MDkiIGN5PSIxNC43MDciIHI9IjEuODcyIiBmaWxsPSJub25lIiBzdHlsZT0iZmlsbDojZmZmO2ZpbGwtb3BhY2l0eTowO3N0cm9rZTojZmZmO3N0cm9rZS13aWR0aDouODtzdHJva2UtZGFzaGFycmF5Om5vbmU7c3Ryb2tlLW9wYWNpdHk6MSIvPjxjaXJjbGUgY3g9IjczLjMwMiIgY3k9IjIxLjA0OSIgcj0iMS44NzIiIGZpbGw9Im5vbmUiIHN0eWxlPSJmaWxsOiNmZmY7ZmlsbC1vcGFjaXR5OjA7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOi44O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxIi8+PGNpcmNsZSBjeD0iODAuNDc3IiBjeT0iMjIuNTk2IiByPSIxLjg3MiIgZmlsbD0ibm9uZSIgc3R5bGU9ImZpbGw6I2ZmZjtmaWxsLW9wYWNpdHk6MDtzdHJva2U6I2ZmZjtzdHJva2Utd2lkdGg6Ljg7c3Ryb2tlLWRhc2hhcnJheTpub25lO3N0cm9rZS1vcGFjaXR5OjEiLz48Y2lyY2xlIGN4PSI3OC41MyIgY3k9IjE2LjM2OSIgcj0iMS44NzIiIGZpbGw9Im5vbmUiIHN0eWxlPSJmaWxsOiNmZmY7ZmlsbC1vcGFjaXR5OjA7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOi44O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxIi8+PGNpcmNsZSBjeD0iNjcuMjI3IiBjeT0iMjMuNDQ2IiByPSIxLjg3MiIgZmlsbD0ibm9uZSIgc3R5bGU9ImZpbGw6I2ZmZjtmaWxsLW9wYWNpdHk6MDtzdHJva2U6I2ZmZjtzdHJva2Utd2lkdGg6Ljg7c3Ryb2tlLWRhc2hhcnJheTpub25lO3N0cm9rZS1vcGFjaXR5OjEiLz48Y2lyY2xlIGN4PSI3Ni4zNjgiIGN5PSIyNy45NiIgcj0iMS44NzIiIGZpbGw9Im5vbmUiIHN0eWxlPSJmaWxsOiNmZmY7ZmlsbC1vcGFjaXR5OjA7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOi44O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxIi8+PHBhdGggZD0ibTc3LjUwNiAyNi40NzQgMS44MzMtMi4zOTJNNzAuNzEyIDE2LjM0N2wxLjY4NyAzLjA2M002OC45NjggMjIuNzZsMi41OTMtMS4wMjRNNzcuMTM1IDE3LjYxOCA3NC42OTcgMTkuOE03NS4xMzIgMjEuNDQ0bDMuNTE1Ljc1N003OS4wODkgMTguMTU1bC44MyAyLjY1NCIgc3R5bGU9ImZpbGw6bm9uZTtmaWxsLXJ1bGU6ZXZlbm9kZDtzdHJva2U6I2ZmZjtzdHJva2Utd2lkdGg6Ljg7c3Ryb2tlLWxpbmVjYXA6YnV0dDtzdHJva2UtbGluZWpvaW46bWl0ZXI7c3Ryb2tlLWRhc2hhcnJheTpub25lO3N0cm9rZS1vcGFjaXR5OjEiLz48L2c+PC9zdmc+"></a>
          <a href="https://docs.ricgraph.eu"><img alt="Ricgraph documentation website" src="https://img.shields.io/badge/doc%20website-docs.ricgraph.eu-blue?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI3MC43NTIiIGhlaWdodD0iNzAuNzYxIiB2aWV3Qm94PSIwIDAgMTguNzIgMTguNzIyIj48ZyBzdHlsZT0ic3Ryb2tlOiNmZmY7c3Ryb2tlLW9wYWNpdHk6MSIgdHJhbnNmb3JtPSJtYXRyaXgoMS4wNTIwNCAwIDAgMS4wNTIwNCAtNjguMzM1IC0xMy4wODMpIj48Y2lyY2xlIGN4PSI2OS44MDkiIGN5PSIxNC43MDciIHI9IjEuODcyIiBmaWxsPSJub25lIiBzdHlsZT0iZmlsbDojZmZmO2ZpbGwtb3BhY2l0eTowO3N0cm9rZTojZmZmO3N0cm9rZS13aWR0aDouODtzdHJva2UtZGFzaGFycmF5Om5vbmU7c3Ryb2tlLW9wYWNpdHk6MSIvPjxjaXJjbGUgY3g9IjczLjMwMiIgY3k9IjIxLjA0OSIgcj0iMS44NzIiIGZpbGw9Im5vbmUiIHN0eWxlPSJmaWxsOiNmZmY7ZmlsbC1vcGFjaXR5OjA7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOi44O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxIi8+PGNpcmNsZSBjeD0iODAuNDc3IiBjeT0iMjIuNTk2IiByPSIxLjg3MiIgZmlsbD0ibm9uZSIgc3R5bGU9ImZpbGw6I2ZmZjtmaWxsLW9wYWNpdHk6MDtzdHJva2U6I2ZmZjtzdHJva2Utd2lkdGg6Ljg7c3Ryb2tlLWRhc2hhcnJheTpub25lO3N0cm9rZS1vcGFjaXR5OjEiLz48Y2lyY2xlIGN4PSI3OC41MyIgY3k9IjE2LjM2OSIgcj0iMS44NzIiIGZpbGw9Im5vbmUiIHN0eWxlPSJmaWxsOiNmZmY7ZmlsbC1vcGFjaXR5OjA7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOi44O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxIi8+PGNpcmNsZSBjeD0iNjcuMjI3IiBjeT0iMjMuNDQ2IiByPSIxLjg3MiIgZmlsbD0ibm9uZSIgc3R5bGU9ImZpbGw6I2ZmZjtmaWxsLW9wYWNpdHk6MDtzdHJva2U6I2ZmZjtzdHJva2Utd2lkdGg6Ljg7c3Ryb2tlLWRhc2hhcnJheTpub25lO3N0cm9rZS1vcGFjaXR5OjEiLz48Y2lyY2xlIGN4PSI3Ni4zNjgiIGN5PSIyNy45NiIgcj0iMS44NzIiIGZpbGw9Im5vbmUiIHN0eWxlPSJmaWxsOiNmZmY7ZmlsbC1vcGFjaXR5OjA7c3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOi44O3N0cm9rZS1kYXNoYXJyYXk6bm9uZTtzdHJva2Utb3BhY2l0eToxIi8+PHBhdGggZD0ibTc3LjUwNiAyNi40NzQgMS44MzMtMi4zOTJNNzAuNzEyIDE2LjM0N2wxLjY4NyAzLjA2M002OC45NjggMjIuNzZsMi41OTMtMS4wMjRNNzcuMTM1IDE3LjYxOCA3NC42OTcgMTkuOE03NS4xMzIgMjEuNDQ0bDMuNTE1Ljc1N003OS4wODkgMTguMTU1bC44MyAyLjY1NCIgc3R5bGU9ImZpbGw6bm9uZTtmaWxsLXJ1bGU6ZXZlbm9kZDtzdHJva2U6I2ZmZjtzdHJva2Utd2lkdGg6Ljg7c3Ryb2tlLWxpbmVjYXA6YnV0dDtzdHJva2UtbGluZWpvaW46bWl0ZXI7c3Ryb2tlLWRhc2hhcnJheTpub25lO3N0cm9rZS1vcGFjaXR5OjEiLz48L2c+PC9zdmc+"></a>
          <a href="https://github.com/UtrechtUniversity/ricgraph"><img alt="GitHub Ricgraph" src="https://img.shields.io/badge/GitHub-UtrechtUniversity/ricgraph-blue?logo=github"></a>
          <img alt="GitHub release date" src="https://img.shields.io/github/release-date/UtrechtUniversity/ricgraph?color=%234c1&logo=github">
          <a href="https://github.com/UtrechtUniversity/ricgraph/releases"><img alt="GitHub latest release" src="https://img.shields.io/github/release/UtrechtUniversity/ricgraph?color=%234c1&logo=github"></a>
          <img alt="GitHub commits since latest release" src="https://img.shields.io/github/commits-since/UtrechtUniversity/ricgraph/latest?color=%234c1&logo=github">
          <img alt="GitHub last commit" src="https://img.shields.io/github/last-commit/UtrechtUniversity/ricgraph?color=%234c1&logo=github">
          <a href="https://pypi.org/project/ricgraph"><img alt="PyPI version" src="https://img.shields.io/pypi/v/ricgraph?label=PyPI%20version&color=%234c1&logo=pypi&logoColor=ffffff"></a>
          <a href="https://pypistats.org/packages/ricgraph"><img alt="PyPI downloads" src="https://img.shields.io/pypi/dm/ricgraph?label=PyPI%20downloads&color=%234c1&logo=pypi&logoColor=ffffff"></a>
  page-footer: 
    background: primary
    left:
      # Do not change '#XX.YY#' below, it will be modified by the Makefile.
      - text: >
          This is documentation for version #XX.YY# of Ricgraph - Research 
          in context graph.
          For more information about Ricgraph, Ricgraph Explorer, and the
          Ricgraph REST API, please read the reference publication 
          <a href="https://doi.org/10.1016/j.softx.2024.101736">
          https://doi.org/10.1016/j.softx.2024.101736</a>, visit the website 
          <a href=https://www.ricgraph.eu>www.ricgraph.eu</a>, 
          or go to the GitHub
          repository <a href=https://github.com/UtrechtUniversity/ricgraph>
          https://github.com/UtrechtUniversity/ricgraph</a>. 

format:
  html:
    theme: 
      - cosmo
      - ricgraph.scss
    toc: true
    number-sections: true
    lightbox: true
    filters:
      - convert_scripts/renumber_sections.lua
      - convert_scripts/set_webpage_title.lua
    # The font used on the webpages is determined by the 'fonts.' below and 
    # a setting in ricgraph.scss.
    # Android has Progressive Web Apps, see file manifest.json.
    # IOS does not have it, it uses the "apple-touch-icon".
    include-in-header:
      - text: |
          <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
          <link rel='manifest' href='/manifest.json'>
          <link rel='apple-touch-icon' sizes='76x76' href='/images/icons/ios/ricgraph-icon-76x76.png'>
          <link rel='apple-touch-icon' sizes='120x120' href='/images/icons/ios/ricgraph-icon-120x120.png'>
          <link rel='apple-touch-icon' sizes='152x152' href='/images/icons/ios/ricgraph-icon-152x152.png'>
          <link rel='apple-touch-icon' sizes='180x180' href='/images/icons/ios/ricgraph-icon-180x180.png'>

keywords:
  - "Research in context graph"
  - "Ricgraph"
  - "Ricgraph Explorer"
  - "Ricgraph REST API"
  - "Data enrichment"
  - "Data harvesting"
  - "Data linking"
  - "Enrichment"
  - "Graph"
  - "Graph database"
  - "Harvest"
  - "Harvest data"
  - "Harvester"
  - "Knowledge graph"
  - "Linked data"
  - "Metadata"
  - "Utrecht University"
  - "Visualization"

