# ########################################################################
#
# Documentation Ricgraph - Research in context graph
#
# ########################################################################
#
# MIT License
# Copyright (c) 2025 Rik D.T. Janssen
#
# ########################################################################
#
# This file is the Quarto config file to generate the Ricgraph
# documentation website.
#
# Original version Rik D.T. Janssen, February 2025.
#
# ########################################################################

project:
  output-dir: ../build_documentation
  type: website
  render:
    # The first here will be referred to in 'index.html'.
    - website/what-is-ricgraph.md
    - "website/*.md"
  
website:
  title: "Website Ricgraph - Research in context graph"
  description: "This is the website for Ricgraph - Research in context graph"
  favicon: website/images/favicon.ico
  search: true
  sidebar:
    border: false
    title: "Research in context graph Website"
    style: docked
    logo: website/images/ricgraph_logo.png
    logo-alt: "Ricgraph logo"
    search: true
    background: primary
    collapse-level: 1
    contents:
      - text: "What is Ricgraph?"
        href: website/what-is-ricgraph.md
      - text: "Learn more"
        href: website/learn-more-about-ricgraph.md
      - section: "Testing"
        contents:
          - text: "Again read more"
            href: website/read-more-about-ricgraph.md
          - text: "And even more"
            href: website/read-more-about-ricgraph.md
          - text: "Test"
            href: website/test-ricgraph.md
      - text: "Read more"
        href: website/read-more-about-ricgraph.md
      - text: "Get Ricgraph"
        href: website/get-ricgraph.md
      - text: "Contact"
        href: website/contact.md
    footer: >
          [![DOI Ricgraph software](https://img.shields.io/badge/DOI%20software-10.5281/zenodo.7524314-blue)](https://doi.org/10.5281/zenodo.7524314)
          [![DOI Ricgraph reference publication](https://img.shields.io/badge/DOI%20publication-10.1016%2Fj.softx.2024.101736-blue)](https://doi.org/10.1016/j.softx.2024.101736)
          [![Ricgraph website](https://img.shields.io/badge/website-www.ricgraph.eu-blue)](https://www.ricgraph.eu)
          [![Ricgraph documentation website](https://img.shields.io/badge/docs%20website-docs.ricgraph.eu-blue)](https://docs.ricgraph.eu)
          [![GitHub Ricgraph](https://img.shields.io/badge/GitHub-UtrechtUniversity/ricgraph-blue)](https://github.com/UtrechtUniversity/ricgraph)
          ![GitHub release date](https://img.shields.io/github/release-date/UtrechtUniversity/ricgraph?color=%234c1)
          [![GitHub latest release](https://img.shields.io/github/release/UtrechtUniversity/ricgraph?color=%234c1)](https://github.com/UtrechtUniversity/ricgraph/releases)
          ![GitHub commits since latest release](https://img.shields.io/github/commits-since/UtrechtUniversity/ricgraph/latest?color=%234c1)
          ![GitHub last commit](https://img.shields.io/github/last-commit/UtrechtUniversity/ricgraph?color=%234c1)
          [![PyPI version](https://img.shields.io/pypi/v/ricgraph?label=PyPI%20version&color=%234c1)](https://pypi.org/project/ricgraph)
          [![PyPI downloads](https://img.shields.io/pypi/dm/ricgraph?label=PyPI%20downloads&color=%234c1)](https://pypistats.org/packages/ricgraph)
  page-footer: 
    background: primary
    left:
      # Do not change '#XX.YY#' below, it will be modified by the Makefile.
      - text: >
          You are visiting one of the Ricgraph websites 
          <a href="www.ricgraph.eu" style="fontsize: 50%">
          www.ricgraph.eu</a>,
          <a href="www.ricgraph.nl" style="fontsize: 50%">
          www.ricgraph.nl</a>, or
          <a href="www.ricgraph.com" style="fontsize: 50%">
          www.ricgraph.com</a>.
    #center:
    #  - text: ""
    #right:
      #- text: ""

format:
  html:
    grid:
      sidebar-width: 350px
    theme: 
      - cosmo
      - ricgraph.scss
    toc: true
    lightbox: true
    filters:
      - convert_scripts/fix_mdtohtml_links.lua
    # The font used on the webpages is determined by the 'fonts.' below and 
    # a setting in ricgraph.scss.
    include-in-header:
      - text: |
          <link href='https://fonts.googleapis.com/css?family=Open+Sans' 
          rel='stylesheet' type='text/css'>

keywords:
  - "Research in context graph"
  - "Ricgraph"
  - "Ricgraph Explorer"
  - "Ricgraph REST API"
  - "Data enrichment"
  - "Data harvesting"
  - "Data linking"
  - "Enrichment"
  - "Graph"
  - "Graph database"
  - "Harvest"
  - "Harvest data"
  - "Harvester"
  - "Knowledge graph"
  - "Linked data"
  - "Metadata"
  - "Utrecht University"
  - "Visualization"

